### ISSUE TITLE
[FEATURE]: annotate container according to OpenContainers labels specification

### ISSUE THREAD

**Issue by shanduur-auto** [registry-operator/registry-operator#3]
### Is your feature request related to a problem? Please describe.

This feature request proposes implementing annotation of containers according to the OpenContainers labels specification, providing a standardized way to categorize and label containers.

### Describe the solution you'd like.

Following the annotations specification by OpenContainers:
- https://github.com/opencontainers/image-spec/blob/main/annotations.md

### Describe alternatives you've considered.

N/A

**Comment by shanduur** [comment]
Consider adding those only in the CI builds:
- https://github.com/marketplace/actions/build-and-push-docker-images#inputs

Here is the aforementioned GH Action in our repo:
- https://github.com/registry-operator/registry-operator/blob/main/.github/workflows/release.yaml

See GitHub events for the documentation of the Event object, and understanding how to set the dynamic values:
- https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28
